### ISSUE TITLE
Security/Use in public repos

### ISSUE THREAD

**Issue by Mic92** [hercules-ci/hercules-ci-effects#31]
From this description it is not yet clear under where hercules ci evaluates effects: https://docs.hercules-ci.com/hercules-ci-effects/guide/deploy-a-nixos-machine/

Could someone add effects as a pull request on my machine and use it to execute commands on my agents?

**Comment by roberth** [comment]
Effects run on linux in a sandbox with access to configured secrets, but no access to the host file system, except for the Nix store.

Currently the security model is to trust refs that are in the repository itself, meaning only those with write access to the repo can use your configured secrets and Nix store. A pull request from a fork won't be built, until you or a bot like bors "approve" it by pushing it to a local ref.

**Comment by Mic92** [comment]
Ok, but it can still access the network as it can deploy NixOS? Also this means it adds unencrypted secrets to the world-readable nix store?

**Comment by roberth** [comment]
It will not add unencrypted secrets to the Nix store unless you ask it to. The secrets are written to a regular file that is made available in the effects sandbox, without involving the store.
Only secrets specified in the values of `secretsMap` will be copied into the sandbox, using the attribute names as secret names. The file is pointed to by `$HERCULES_CI_SECRETS_JSON` in the sandbox environment.
It can be used by functions like [readSecretString](https://docs.hercules-ci.com/hercules-ci-effects/reference/bash-functions/readsecretstring/).

The [`runNixOS`](https://docs.hercules-ci.com/hercules-ci-effects/reference/nix-functions/runnixos/) effect works in the same way. You add an SSH key for the host you want to deploy to your agent's `secrets.json`, which is unencrypted but only needs to be readable by the agent user (NixOS module: `hercules-ci-agent`). Now the expressions in your repositories can reference the SSH key for use in an effect.

The sandbox does not have direct access to the host, so it needs to use ssh or similar. For now though, I don't recommend to CD the agent host, because agent restarts interfere with running effects, including the self-deployment. You can follow https://github.com/hercules-ci/hercules-ci-agent/issues/273 for updates about this feature. However, I do find the effects sandbox by itself useful for hermetic deployment, using `hci effect run` and [`hci secret add`](https://docs.hercules-ci.com/hercules-ci-agent/hci/secret/add/) to manage user local secrets for `hci` in `~/.config/hercules-ci/secrets`.

**Comment by Mic92** [comment]
Thanks
